version: "3.8"

services:
  frontend:
    build:
      context: ./function-visualizer-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./function-visualizer-frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
